baseurl = "http://joshuawhite.com/"
languageCode = "en-us"
title = "JOSH'S BLOG"
copyright = "Copyright &copy; 2018 - Joshua White"
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

disqusShortname = "joshuawhite929"
googleAnalytics = "UA-83956916-1"

[author]
    name = "Joshua White"
    github = "joshuawhite929"
    gitlab = ""
    linkedin = "joshuawhite929"
    facebook = ""
    twitter = "joshuawhite929"
    instagram = ""

[params]
    tagline = ""